services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - ml-service
    environment:
      ML_SERVICE_URL: "http://ml-service:8080"
      GROQ_API_KEY: ${GROQ_API_KEY}

  ml-service:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: 0
